export { WebSocketManager, wsManager } from './manager';
export type {
  ConnectionStatus,
  ConnectionStatusCallback,
  ServerToClientEvents,
  ClientToServerEvents,
  JoinRoomPayload,
  RoomJoinedPayload,
  PeerInfo,
  PeerJoinedPayload,
  PeerLeftPayload,
  WebRTCOfferPayload,
  WebRTCAnswerPayload,
  WebRTCIcePayload,
  WebRTCOfferEvent,
  WebRTCAnswerEvent,
  WebRTCIceEvent,
  ErrorPayload,
  TypedSocket,
} from './types';
