#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Re-run memory lives outside the repo (this wizard is about the VPS, not the
# app's local env). Override with ENV_FILE=... if you want it elsewhere.
ENV_FILE="${ENV_FILE:-$HOME/.zvonok-traefik-wizard.env}"

banner "Traefik gateway — multi-site VPS setup"

# Run a command on the VPS over SSH (uses your regular key/agent auth).
_vps() {
  ssh -o ConnectTimeout=15 "${VPS_USER}@${VPS_HOST}" "$@"
}

# ── Stage 1: SSH connection ───────────────────────────────────────────────
stage "VPS connection"
say "This wizard prepares ~/gateway, redeploys zvonok behind Traefik,"
say "then starts the gateway. See docs/traefik-migration-plan.md."
ask VPS_HOST "VPS hostname or IP:"
ask VPS_USER "SSH user (the one deploys use, usually deploy):"
write_env VPS_HOST "$VPS_HOST"
write_env VPS_USER "$VPS_USER"
step "Testing SSH, Docker and the project directory…"
if _vps 'docker compose version >/dev/null && test -d ~/zvonOK'; then
  note "SSH OK · Docker Compose v2 present · ~/zvonOK exists"
else
  warn "SSH works but the check failed — is Docker installed and is ~/zvonOK in place?"
  warn "Fix that, then re-run this wizard (it remembers your answers)."
  exit 1
fi

# ── Stage 2: DNS ──────────────────────────────────────────────────────────
stage "DNS check"
ask SITE_ADDRESS "Zvonok domain (SITE_ADDRESS, e.g. chat.example.com):"
write_env SITE_ADDRESS "$SITE_ADDRESS"
resolved=$(dig +short "$SITE_ADDRESS" 2>/dev/null | grep -E '^[0-9.]+$' | tail -n1 || true)
vps_ip=$(_vps 'curl -fsS4 https://api.ipify.org' 2>/dev/null || true)
say "DNS resolves to: ${resolved:-<no answer>}"
say "VPS public IP:    ${vps_ip:-<unknown>}"
if [[ -n "$resolved" && -n "$vps_ip" && "$resolved" == "$vps_ip" ]]; then
  note "OK — the domain points at this VPS"
else
  warn "Mismatch! Fix the A record at your registrar before continuing."
fi
note "Every future site needs its own A record: <sub>.<domain> → ${vps_ip:-<VPS IP>}"
pause "Continue?"

# ── Stage 3: network + gateway files (not started) ────────────────────────
stage "Shared network + gateway files"
say "Traefik must NOT start yet — the running zvonok-caddy still owns"
say "ports 80/443 and Docker would refuse to bind them."
step "Creating the shared docker network 'web' (idempotent)…"
_vps 'docker network create web 2>/dev/null || true'
note "✓ network 'web' ready"
ask ACME_EMAIL "Email for Let's Encrypt expiry notices:"
write_env ACME_EMAIL "$ACME_EMAIL"
step "Writing ~/gateway/{docker-compose.yml,.env,acme.json}…"
_vps 'mkdir -p ~/gateway'
_vps 'cat > ~/gateway/docker-compose.yml' <<'YAML'
services:
  traefik:
    image: traefik:v3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # HTTP/3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    networks:
      - web
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true
YAML
printf 'ACME_EMAIL=%s\n' "$ACME_EMAIL" | _vps 'cat > ~/gateway/.env'
_vps 'touch ~/gateway/acme.json && chmod 600 ~/gateway/acme.json'
note "✓ gateway prepared (files only — not running)"

# ── Stage 4: redeploy zvonok ──────────────────────────────────────────────
stage "Redeploy zvonok behind the gateway"
say "The new compose takes 80/443 away from caddy and attaches it to the"
say "gateway. The site is DOWN from the end of the deploy until stage 5."
repo_slug=$(git remote get-url origin 2>/dev/null | sed -E 's#.*[:/]([^/]+/[^/.]+)(\.git)?$#\1#' || true)
if [[ -n "$repo_slug" ]]; then
  open_url "https://github.com/${repo_slug}/actions/workflows/deploy.yml"
else
  warn "couldn't derive the repo from git remote — open the Actions → Deploy page yourself"
fi
step "Merge the migration branch into main and push."
step "On the Deploy workflow page: 'Run workflow' → branch main → Run."
step "Wait for all jobs (build + deploy) to finish green."
pause "Deploy finished green? Press Enter to check the VPS…"
caddy_ports=$(_vps 'docker ps --filter name=zvonok-caddy --format "{{.Ports}}"' 2>/dev/null || true)
if [[ -z "$caddy_ports" ]]; then
  note "✓ zvonok-caddy publishes no host ports"
else
  warn "zvonok-caddy still publishes: ${caddy_ports} — the deploy may not be done; re-check before continuing"
fi
web_members=$(_vps 'docker network inspect web --format "{{range .Containers}}{{.Name}} {{end}}"' 2>/dev/null || true)
say "network 'web' members: ${web_members:-<none>}"
[[ "$web_members" == *zvonok-caddy* ]] && note "✓ zvonok-caddy joined the gateway network" \
                                      || warn "zvonok-caddy is NOT on the web network — check the deploy"
pause "Continue?"

# ── Stage 5: start the gateway ────────────────────────────────────────────
stage "Start the Traefik gateway"
say "Ports 80/443 are free now; Traefik will bind them and route to"
say "zvonok by its Host(\`…\`) label. First HTTPS request also fetches"
say "the Let's Encrypt certificate (a few seconds)."
confirm "Start traefik now?" || { warn "aborted — site stays down until you run: cd ~/gateway && docker compose up -d"; exit 1; }
_vps 'cd ~/gateway && docker compose up -d'
sleep 3
if _vps 'docker ps --filter name=traefik --filter status=running --format "{{.Names}}"' | grep -q traefik; then
  note "✓ traefik is running"
else
  warn "traefik is not running — inspect: ssh ${VPS_USER}@${VPS_HOST} 'docker logs traefik'"
  exit 1
fi
_vps 'docker logs traefik --tail 15 2>&1'

# ── Stage 6: verify + rollback cheat-sheet ────────────────────────────────
stage "Verify"
step "Probing https://${SITE_ADDRESS} (first request may take a few extra seconds)…"
code=""
for _ in 1 2 3 4 5; do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "https://${SITE_ADDRESS}" 2>/dev/null || true)
  [[ "$code" == "200" ]] && break
  sleep 4
done
say "HTTPS status: ${code:-<no answer>}"
redir=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "http://${SITE_ADDRESS}" 2>/dev/null || true)
say "HTTP→HTTPS redirect status: ${redir:-<no answer>} (expect 308)"
api=$(curl -s --max-time 15 "https://${SITE_ADDRESS}/version" 2>/dev/null || true)
say "API /version: ${api:-<no answer>}"
[[ "$code" == "200" ]] && note "✓ site is live behind the gateway" \
                      || warn "not 200 yet — check: ssh ${VPS_USER}@${VPS_HOST} 'docker logs traefik --tail 50'"
pause "Open the site, log in, start a test call. Done? Press Enter."
say "Rollback (if anything is off):"
note "  ssh ${VPS_USER}@${VPS_HOST} 'cd ~/gateway && docker compose down'"
note "  git revert <migration-commit> && push → run the Deploy workflow"
note "  (old caddy re-binds 80/443 and manages its own TLS again)"
say "Future sites: see 'Adding a New Site to the VPS' in docs/deployment.md"

finish
